config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path

from . import views

app_name = 'project'
urlpatterns = [
    path('', views.index, name='index'),
    path('uploaded_photo/', views.uploaded_photo, name='uploaded_photo'),
    path('uploaded_photo/update/', views.update, name='update')
]

project/models.py
import os
from functools import partial

from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models


# Create your models here
def _update_filename(instance, filename, path):
    path = path

    filename = "project_image.jpg"

    return os.path.join(path, filename)


def upload_to(path):
    return partial(_update_filename, path=path)


class OverwriteStorage(FileSystemStorage):
    """
    Overwrites the file name project_image if it already exits
    """

    def get_available_name(self, name, max_length=500):
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name


class Image(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to=upload_to('images/'), storage=OverwriteStorage())


class BaseAdjustment(models.Model):
    is_gray = models.BooleanField(default=False)


class RGBAdjustments(models.Model):
    red_value = models.IntegerField(default=100)
    green_value = models.IntegerField(default=100)
    blue_value = models.IntegerField(default=100)


class Difference(models.Model):
    is_diff = models.BooleanField(default=False)


class Color:
    def __init__(self, name, val):
        self.name = name
        self.val = val

project/forms.py
# forms.py 
from django import forms

from .models import *


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['name', 'image']

# class BaseAdjustmentForm(forms.Form):
#    is_gray_scale = forms.BooleanField(initial=False)
#
#
# class RGBAdjustmentForm(forms.ModelForm):
#    adjustment = forms.BooleanField(initial=False)
#    r = forms.IntegerField(max_value=100, min_value=0)
#    g = forms.IntegerField(max_value=100, min_value=0)
#    b = forms.IntegerField(max_value=100, min_value=0)

project/views.py
from PIL import Image as Img
from django.shortcuts import render, get_object_or_404

from .ImageAdjuster import _base, _histogram, entropy, _adjust_brightness, _difference_transformation, _reset
from .constants import *
from .forms import *

SLIDERS = ()
CONTEXT = {}
UPLOADED_IMG = False
STARTUP = True


# Create your views here.
def index(request):
    global STARTUP, SLIDERS, CONTEXT

    if STARTUP:
        val = get_object_or_404(RGBAdjustments, pk=1)
        SLIDERS = (
            Color('Red', val.red_value),
            Color('Green', val.green_value),
            Color('Blue', val.blue_value)
        )

        base = get_object_or_404(BaseAdjustment, pk=1)
        base.is_gray = False
        base.save()

        CONTEXT = {
            'img_obj': EDIT_IMG_PATH,
            'form': ImageForm(),
            'base': 'Gray',
            'sliders_': SLIDERS,
            'diff_txt': 'Difference'
        }
        STARTUP = False

    return render(request, 'index.html', CONTEXT)


def uploaded_photo(request):
    global UPLOADED_IMG, CONTEXT
    if request.method == 'POST' and request.FILES is not None:
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            try:
                image = Img.open(PROJ_IMG_PATH)
                image.save(EDIT_IMG_PATH)
            except IOError as e:
                print(e)
                print('Could not duplicate image for edit.')
                raise e

            UPLOADED_IMG = True
            base = get_object_or_404(BaseAdjustment, pk=1)
            base.is_gray = False
            base.save()
            diff = get_object_or_404(Difference, pk=1)
            diff.is_diff = False
            diff.save()

            _histogram()

            CONTEXT.update({
                'url_histogram': str(HIST_IMG_PATH[1:]),
                'img_url': str(EDIT_IMG_PATH[1:]),
                'entropy': entropy(),
            })
    else:
        index(request)

    return render(request, 'index.html', CONTEXT)


def update(request):
    if UPLOADED_IMG:
        base = get_object_or_404(BaseAdjustment, pk=1)
        if 'base' in request.POST:
            base.is_gray = not base.is_gray
            base.save()
            _base(base.is_gray)
            CONTEXT['base'] = 'Reset' if base.is_gray else 'Gray'
            CONTEXT['hist_base_txt'] = 'Gray' if base.is_gray else 'RGB'
        elif 'basic' in request.POST and not base.is_gray:
            rgb = get_object_or_404(RGBAdjustments, pk=1)
            rgb.red_value = int(request.POST['Red_slider'])
            rgb.green_val = int(request.POST['Green_slider'])
            rgb.blue_value = int(request.POST['Blue_slider'])
            rgb.save()

            SLIDERS[0].val = rgb.red_value
            SLIDERS[1].val = rgb.green_val
            SLIDERS[2].val = rgb.blue_value

            _adjust_brightness(rgb.red_value, rgb.green_val, rgb.blue_value)

        elif 'diff_trans' in request.POST:
            diff = get_object_or_404(Difference, pk=1)
            if not diff.is_diff:
                _difference_transformation()
                diff.is_diff = True
                diff.save()
                base.is_gray = True
                base.save()
                CONTEXT['diff_txt'] = 'Reset'
            else:
                _reset()
                diff.is_diff = False
                diff.save()
                base.is_gray = False
                base.save()
                CONTEXT['diff_txt'] = 'Difference'
                CONTEXT['hist_base_txt'] = 'RGB'
        elif 'reset' in request.POST:
            _reset()

        _histogram()
        CONTEXT['entropy'] = entropy()

    return render(request, 'index.html', CONTEXT)

project/templates/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'project/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'project/action.js' %}"></script>
</head>
<span class="bg_bar" id="top_bg_bar"></span>
<div>
    <div>
        <h1>Image Enhancement</h1>
        <div id="main_img_container">
            <img alt="User Image" id="img_main" src="{{ img_url }}">
        </div>
    </div>
    <div>
        <form action="{% url 'project:uploaded_photo' %}" autocomplete="off" enctype="multipart/form-data" id="upload_form"
              method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" value="Upload">Upload</button>
        </form>
    </div>
</div>

<!-- Adjustments Panel -->
<div class="panel" id="right_sidebar">
    <h2>Basic Adjustments</h2>
    <form action="{% url 'project:update' %}" method="POST">
        {% csrf_token %}
        <button id="btn_grayscale" name="base">{{ base }}</button>
    </form>
    <form action="{% url 'project:update' %}" id="basic_form" method="POST">
        {% csrf_token %}
        <label class="switch">
            <input checked onclick="changeLabel(this)" type="checkbox">
            <span class="toggle round"></span>
        </label>
        <label id="switch_label">Value: (Red, Green, Blue)</label>
        <div>
            {% for s in sliders_ %}
            <label for="{{ s.name }}_slider">{{ s.name }} <span id="{{ s.name }}_span">{{ s.val }} %</span></label>
            <input class="slider brightness" id="{{ s.name }}_slider" max="100" min="0"
                   name="{{ s.name }}_slider" oninput="getValue(this, '{{ s.name }}_span')" step="1" type="range"
                   value="{{ s.val }}">
            <br>
            {% endfor %}
        </div>
        <button name="basic" type="submit">Update</button>
        <button name="reset" type="submit">Reset</button>
    </form>
    <h2>Advanced Adjustments</h2>
    <form action="{% url 'project:update' %}" id="advanced_form" method="POST">
        {% csrf_token %}
        <button name="diff_trans">{{ diff_txt }}</button>
    </form>
    <h2>Metrics</h2>
    <div>Entropy: {{ entropy }}</div>
    <h2>{{ hist_base_txt }} Histogram</h2>
    <div><img alt="Histogram" id="img_histogram" src="{{ url_histogram }}"/></div>
</div>
<span class="bg_bar" id="bot_bg_bar"></span>

project/templates/project/index.html
{% load static %}
<head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}">
</head>

<img src="{{ img_obj.image.url}}" alt="connect" height="200px" width="auto">

<form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Upload">Upload</button>
</form>

<div class="panel" id="right_sidebar">
        <h1>Image Enhancement</h1>
        <h2>Basic</h2>
        <button>RGB to Grayscale</button>
        <form method = "POST" enctype="multipart/form-data">
            <input type="radio" id="saturation" name="basic_adjustment" value="saturation">
            <label for="saturation">Saturation</label><br>
            <input type="radio" id="brightness" name="basic_adjustment" value="brightness">
            <label for="brightness">Brightness</label><br>
        </form>
        <form method="POST" id="basic_form">
            {% for c in colors %}
                <input name="{{ c }}_slider" type="range" min="0" max="1" value="0.5" step="0.1" class="class_slider" id="{{ c }}_slider_id">
                <label for="{{ c }}_slider">{{ c }}</label><br>
            {% endfor %}
            <button type="submit" value="Update">Update</button>
        </form>
        <h2>Advanced</h2>
        <form method="POST" id="advanced_form">
            <div>Gamma <input type="number" min="0" max="1" value="0.2" step="0.01"></div>
        </form>
</div>
    